import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))


from python_classes.reflection_agent import ReflectionAgent

generator_prompts = [
    {
        "role": "system",
        "content": "Data analyst good at visualizing data. Use Python Pandas to generate code to visualize user data. "
        "When provided with critiques, improve the code to make it more efficient and accurate. and response "
        "with a newly revised code based on the critiques improved code."
    }
]

reflection_prompts = [
    {
        "role": "system",
        "content": "You are a senior data analyst. Given the code generated by the generator block, provide feedback to the generator block. "
        "The feedback should be in the form of a critique of the code. The critique should be in the form of a list of improvements that can be made to the code. "
        "The feedback should be in the form of a list of improvements that can be made to the code. "
    }
]

agent = ReflectionAgent(generator_prompts, reflection_prompts, num_steps=4)
agent.run(
    user_prompt="Write me code to visualize this data in a pie chart. Here is the data: {'data': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'column': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']}")
